/* =====================================================================
   SECTION 31 — CONTENT. This is the file you edit to change the site.
   Everything below is placeholder. In the live build each list maps onto a
   sheet the store owner edits from the admin wizard (Products, Events,
   Gallery, Reviews, StoreSettings), so nothing here is hard-wired to layout.
   ===================================================================== */
const S31 = {
  // true while you are testing: shows the "demo - nothing is sent" notes. Set to false when you go live.
  demo: true,

  // Link-out booking page (Google Calendar appointment page, Calendly...). Leave '' until you have one.
  bookingLink: '',

  // Footer link back to the mall. Set show:false to hide it (for example while ads are under review).
  mallLink: { show: true, href: 'https://indusvalley.earth/', label: 'Indus Valley' },

  // Admin backend: paste your Apps Script web-app URL here (see ADMIN-SETUP.md). '' = use the content in this file.
  api: 'https://script.google.com/macros/s/AKfycbw2t57hCL4K-i3zEI2qOAMQEXhCrJ9_st3xvNM8C9IqWNu0JMu8lNlyUHvctodtLn7h/exec',

  // Pre-launch: hides prices and specials, shows "Notify me" / "Register interest" buttons and an opening banner.
  // Untick "Pre-launch mode" in the admin (Store details) on opening day.
  prelaunch: true,
  launchNote: 'This is a preview while we finalise stock, lessons and prices. Tap Notify me on anything you like and we’ll message you when it’s ready.',

  tagline: 'Classified treasures for the ultimate collector.',

  contact: {
    address: '[Street address goes here]',
    hours: [['Tue – Fri', '10:00 – 18:00'], ['Saturday', '09:00 – 16:00'], ['Sun – Mon', 'Closed']],
    whatsapp: '27000000000',            // digits only, with country code
    instagram: '@section31.za',
    email: 'hello@section31.example'
  },

  zones: [
    { id: 'zone1', short: 'The Floor', no: '01', name: 'Section 31',          role: 'The Floor',           color: '#19e3ff', line: 'Comics, cards, collectables and fandom shelves, plus the Evidence Locker.', pull: 'Wednesday drops' },
    { id: 'zone2', short: 'Kobayashi Maru', no: '02', name: 'The Kobayashi Maru',  role: 'The Learning Zone',   color: '#ffb454', line: 'Lessons in chess, Rubik’s cube and board games, plus puzzles and people-skills challenges.', pull: 'Lessons & challenge nights' },
    { id: 'zone3', short: 'Holodeck', no: '03', name: 'The Holodeck',        role: 'Gaming & Portals',    color: '#b388ff', line: 'Every game: news, how-to-play sessions, challenges with scoreboards, gear and our online channels.', pull: 'Challenges & tournaments' },
    { id: 'zone4', short: 'Spock’s Corner', no: '04', name: 'Spock’s Corner',      role: 'The Intelligence Corner', color: '#5eead4', line: 'Coding, cyber security, engineering and ancient tech. Debates, study groups and tables to book.', pull: 'Debates & study groups' },
    { id: 'zone5', short: 'Ancient X-Files', no: '05', name: 'Ancient X-Files',     role: 'Unsolved Mysteries',  color: '#e6c98a', line: 'The ancient world, every possibility: Sumer, Atlantis, India, Egypt, Africa, ancient astronauts and declassified files.', pull: 'Theory nights' },
    { id: 'zone6', short: 'Transmissions', no: '06', name: 'Transmissions',       role: 'Podcast & Content',   color: '#ff5d6c', line: 'Our podcast, videos, streams and behind the scenes, plus where to listen.', pull: 'New episodes' },
    { id: 'zone7', short: 'Saber Academy', no: '07', name: 'The Saber Academy',   role: 'Star Wars',           color: '#4ade80', line: 'Lightsaber lessons from first stance to full duels, plus lore, cosplay and gear.', pull: 'Saber training nights' }
  ],

  /* ---------------- ZONE 01: SHELVES, STOCK, SPECIALS ----------------
     Live build: each list becomes a sheet staff edit from the admin login
     (Shelves, Stock, Specials). ALL items and prices below are placeholders. */

  delivery: 'Prices shown are in-store prices. Delivery is quoted separately.',

  // One entry per shelf. "story", "dyk" (did you know) and "note" (fun fact) show when a customer opens the shelf.
  shelves: [
    { id: 'comics', name: 'Comics', title: 'Comics & graphic novels',
      story: 'The comic book took off in the 1930s, when newspaper strips were reprinted as booklets. Then Superman arrived in 1938 and the superhero age began.',
      dyk: ['Superman’s debut, Action Comics #1 (1938), cost 10 cents. Top copies have since sold for millions of dollars.',
            'Will Eisner’s A Contract with God (1978) helped make “graphic novel” a household term.',
            'From 1954 the Comics Code seal shaped what US comics could show for decades.'],
      note: 'Stan Lee’s first published work was a short text story in Captain America Comics #3 (1941).' },
    { id: 'manga', name: 'Manga', title: 'Manga',
      story: 'Manga is read right to left, starting from what Western readers think of as the back of the book.',
      dyk: ['Osamu Tezuka, creator of Astro Boy (1952), is often called the “god of manga”.',
            'One Piece has sold more than 500 million copies worldwide.',
            'Weekly Shōnen Jump, the original home of Dragon Ball and Naruto, launched in 1968.'],
      note: 'Most series run chapter by chapter in weekly or monthly magazines first, then get collected into volumes.' },
    { id: 'pokemon', name: 'Pokémon cards', title: 'Pokémon cards',
      story: 'Pokémon began as a Game Boy game in Japan in 1996. The trading card game followed that same year and reached English shelves in 1999.',
      dyk: ['The name is short for “Pocket Monsters”.',
            'Pokémon is often called the highest-grossing media franchise of all time.',
            'Only a handful of Pikachu Illustrator cards were handed out as contest prizes in 1998. One sold for over US$5 million in 2022.'],
      note: 'A first-edition Base Set Charizard is the card most collectors dream of pulling.' },
    { id: 'tcg', name: 'Magic & more', title: 'Trading card games',
      story: 'Magic: The Gathering, designed by maths professor Richard Garfield and released in 1993, created the modern trading card game.',
      dyk: ['Black Lotus, from Magic’s very first set, is one of the most valuable cards ever printed.',
            'Yu-Gi-Oh! started as a manga before its card game launched in 1999.',
            'Serious collectors protect their best cards with sleeves, top-loaders and graded slabs.'],
      note: 'Many players “double-sleeve” their best cards: a snug inner sleeve inside a normal outer one.' },
    { id: 'starwars', name: 'Star Wars', title: 'Star Wars',
      story: 'Star Wars (1977) changed toys forever. Kenner couldn’t make figures fast enough for Christmas, so it sold an empty “Early Bird” certificate box instead.',
      dyk: ['Marvel’s Star Wars comic launched in 1977 and is credited with helping keep Marvel afloat.',
            'In the original trilogy, Yoda was a puppet performed and voiced by Frank Oz.',
            'Original 1970s figures still sealed on their card can be worth thousands.'],
      note: 'As the story goes, R2-D2’s name came from a film editor’s shorthand: “Reel 2, Dialogue 2”.' },
    { id: 'potter', name: 'Harry Potter', title: 'Harry Potter',
      story: 'Harry Potter and the Philosopher’s Stone came out in 1997 with a first print run of just 500 hardbacks.',
      dyk: ['About 300 of those first copies went to libraries.',
            'The manuscript was turned down by about a dozen publishers first.',
            'Quidditch became a real sport. Players now call it “quadball”.'],
      note: 'J.K. Rowling first thought of Harry on a delayed train from Manchester to London in 1990.' },
    { id: 'lotr', name: 'Lord of the Rings', title: 'The Lord of the Rings',
      story: 'J.R.R. Tolkien was born in Bloemfontein, South Africa, in 1892. He later became an Oxford professor and built Middle-earth.',
      dyk: ['Tolkien invented Elvish languages first. Middle-earth grew partly as a home for them.',
            'It was published in three volumes in 1954–55 for practical reasons. Tolkien saw it as one book.',
            'The Return of the King won 11 Oscars, tying the all-time record.'],
      note: 'The Hobbit (1937) grew out of stories Tolkien told his own children.' },
    { id: 'transformers', name: 'Transformers', title: 'Transformers',
      story: 'Transformers arrived in 1984, when Hasbro rebranded Japanese toys from Takara’s Diaclone and Micro Change lines.',
      dyk: ['Marvel launched a Transformers comic the same year, and its writers helped name and shape many characters.',
            'Peter Cullen has voiced Optimus Prime since 1984.',
            'Collectors check paint, joints and whether the original weapons are still there.'],
      note: 'Both the heroic Autobots and the villainous Decepticons come from the planet Cybertron.' },
    { id: 'startrek', name: 'Star Trek', title: 'Star Trek',
      story: 'Star Trek first aired in 1966. The comics followed fast, with Gold Key’s series starting in 1967.',
      dyk: ['The Klingon language was developed by linguist Marc Okrand.',
            'The exact line “Beam me up, Scotty” was never said in the original series.',
            'The transporter was partly a budget idea: beaming down was cheaper to film than landing a ship.'],
      note: 'Fans have translated Hamlet into Klingon.' },
    { id: 'collectables', name: 'Collectables', title: 'Figures, statues & Funko',
      story: 'With collectables, condition is everything. The same figure can be worth very different amounts depending on box, paint and grade.',
      dyk: ['Funko’s Pop! vinyl line launched in 2010 and now runs to thousands of figures.',
            'Some Pops have rarer “chase” variants, packed in limited numbers.',
            'CGC began grading comics in 2000, on a scale from 0.5 to 10.'],
      note: 'Keep figures out of direct sunlight: UV fades paint and yellows clear plastic boxes.' },
    { id: 'games', name: 'D&D & games', title: 'Role-playing & board games',
      story: 'Dungeons & Dragons was published in 1974 by Gary Gygax and Dave Arneson and kick-started tabletop role-playing.',
      dyk: ['The 20-sided die (d20) decides most actions in D&D.',
            'Catan (1995) helped spark the modern board-game boom.',
            'D&D’s fifth edition (2014) brought a huge wave of new players.'],
      note: 'A d20 is an icosahedron, one of the five Platonic solids.' },
    { id: 'chess', zone: 'zone2', name: 'Chess', title: 'Chess',
      story: 'Modern chess settled in Europe around 1500, growing out of older Indian and Persian games. It is still the classic test of planning and patience.',
      dyk: ['FIDE, the world chess federation, was founded in Paris in 1924.',
            'IBM’s Deep Blue beat world champion Garry Kasparov in a match in 1997.',
            '“Checkmate” comes from the Persian “shāh māt”, often translated as “the king is helpless”.'],
      note: 'There are more possible chess games than atoms in the observable universe.' },
    { id: 'cubes', zone: 'zone2', name: 'Rubik’s cube', title: 'Rubik’s cube & speedcubing',
      story: 'Ernő Rubik, a Hungarian architecture lecturer, built the first cube in 1974 to explain how objects move in 3D. It went worldwide in 1980.',
      dyk: ['A 3×3 cube has about 43 quintillion possible positions.',
            'Every position can be solved in 20 moves or fewer. Cubers call it “God’s number”, proven in 2010.',
            'The World Cube Association runs official competitions worldwide, South Africa included.'],
      note: 'Top speedcubers now solve a 3×3 in under four seconds.' },
    { id: 'boardgames', zone: 'zone2', name: 'Board games', title: 'Board games',
      story: 'Board games are some of the oldest games we know. The Royal Game of Ur was played in Mesopotamia about 4,500 years ago.',
      dyk: ['Go is played on a 19×19 board. AlphaGo beat top professional Lee Sedol in 2016.',
            'Morabaraba, a strategy game played across southern Africa, is recognised by Mind Sports South Africa.',
            'Catan (1995) helped spark the modern board-game boom.'],
      note: 'Go has more possible board positions than there are atoms in the observable universe.' },
    { id: 'logic', zone: 'zone2', name: 'Logic puzzles', title: 'Logic & mechanical puzzles',
      story: 'Puzzle boxes, burr puzzles and tangrams have tested minds for centuries. The tangram came from China and swept Europe in the early 1800s.',
      dyk: ['Japanese puzzle boxes from the Hakone region can need dozens of hidden moves to open.',
            'Sudoku has a Japanese name, but its modern form first appeared in a US puzzle magazine in 1979.',
            'A Tower of Hanoi with 64 discs would need over 18 quintillion moves.'],
      note: 'The first crossword was published in the New York World in 1913.' },
    { id: 'people', zone: 'zone2', name: 'People skills', title: 'People-skills challenges',
      story: 'Social-deduction games and team scenarios test what a quiz can’t: communication, trust and decisions under pressure.',
      dyk: ['Mafia, the ancestor of Werewolf, was created by Dmitry Davidoff in Moscow in 1986.',
            'The first real-life escape rooms opened in Japan around 2007.',
            'Teams that can admit mistakes openly tend to learn faster. Researchers call it psychological safety.'],
      note: 'Good escape rooms are built so that no one person can solve them alone.' },
    { id: 'flightsim', zone: 'zone3', name: 'Flight sim', title: 'Flight simulators',
      story: 'Microsoft Flight Simulator first launched in 1982, which makes it one of the longest-running game series of all.',
      dyk: ['Microsoft Flight Simulator (2020) builds its world from real map data, so you can fly over your own street.',
            'Microsoft Flight Simulator 2024 was released in November 2024.',
            'Online networks such as VATSIM let players fly with volunteer air traffic controllers.'],
      note: 'Many real pilots use home simulators to practise procedures between flights.' },
    { id: 'cod', zone: 'zone3', name: 'Call of Duty', title: 'Call of Duty (mobile & PC)',
      story: 'Call of Duty began in 2003 as a World War II shooter on PC and grew into one of the biggest series in gaming.',
      dyk: ['Call of Duty: Mobile launched in 2019 and passed 100 million downloads in its first week.',
            'Warzone, the free battle royale, arrived in 2020.',
            'The Call of Duty League is the series’ professional esports league.'],
      note: 'COD Mobile and the PC/console games keep separate ranks, so you can climb both.' },
    { id: 'mobile', zone: 'zone3', name: 'Mobile', title: 'Mobile gaming',
      story: 'Mobile is now the biggest part of the games market by revenue: the most popular gaming device is already in your pocket.',
      dyk: ['Snake on Nokia phones (1997) was many people’s first mobile game.',
            'Pokémon GO (2016) got millions of players walking outside to play.',
            'Many mobile games now support Bluetooth controllers.'],
      note: 'Mobile esports draw huge audiences, especially across Asia.' },
    { id: 'pc', zone: 'zone3', name: 'PC & esports', title: 'PC gaming & esports',
      story: 'PC gaming covers everything from strategy to esports. Before online play was easy, LAN parties were how friends played together.',
      dyk: ['One of the first esports events was a Spacewar! contest at Stanford in 1972.',
            'Steam launched in 2003.',
            'Counter-Strike started in 1999 as a fan-made mod for Half-Life.'],
      note: 'Speedrunning took off in the 1990s with Doom players sharing recordings of their fastest runs.' },
    { id: 'console', zone: 'zone3', name: 'Console', title: 'Console gaming',
      story: 'Home consoles began with the Magnavox Odyssey in 1972. Today they share many games with PC, often with cross-play.',
      dyk: ['The PlayStation 2 is the best-selling console ever, with more than 150 million sold.',
            'Nintendo started out in 1889, making playing cards.',
            'The first Xbox launched in 2001.'],
      note: 'Cross-play lets console and PC players join the same matches in many games.' },
    { id: 'retro', zone: 'zone3', name: 'Retro & arcade', title: 'Retro & arcade',
      story: 'The arcade era took off with Pong (1972) and Space Invaders (1978), and the classics are still a test of pure skill.',
      dyk: ['Pac-Man (1980) was designed to appeal to more than just fans of shooting games.',
            'Tetris was created by Alexey Pajitnov in Moscow in 1984.',
            'A popular story says Space Invaders caused a coin shortage in Japan.'],
      note: 'The Konami Code (↑↑↓↓←→←→BA) first appeared in Gradius on the NES in 1986.' },
    { id: 'coding', zone: 'zone4', name: 'Coding', title: 'Coding',
      story: 'Ada Lovelace published what is often called the first computer program in 1843, written for Charles Babbage’s Analytical Engine.',
      dyk: ['The first logged “computer bug” was a real moth, found in a Harvard relay in 1947.',
            'Python is named after Monty Python, not the snake.',
            'Git was created by Linus Torvalds in 2005.'],
      note: 'Grace Hopper’s team built one of the first compilers in the early 1950s.' },
    { id: 'cyber', zone: 'zone4', name: 'Cyber security', title: 'Cyber security',
      story: 'Cyber security is about protecting people, not just computers. Most attacks start with a message designed to trick someone.',
      dyk: ['The Morris worm (1988) was one of the first internet worms to spread widely.',
            'Capture-the-flag (CTF) contests are how many security professionals learned their skills.',
            'South Africa’s POPIA law protects personal information and took full effect in 2021.'],
      note: 'A long passphrase of random words is usually stronger, and easier to remember, than a short complicated password.' },
    { id: 'engineering', zone: 'zone4', name: 'Engineering', title: 'Engineering',
      story: 'Engineering is problem-solving with real-world limits: cost, materials, safety and time.',
      dyk: ['The Great Pyramid of Giza was the tallest human-made structure for about 3,800 years.',
            'The Raspberry Pi launched in 2012 to help teach computing.',
            'SALT, near Sutherland in the Northern Cape, is the largest single optical telescope in the southern hemisphere.'],
      note: 'Engineers use a “factor of safety”: they build things stronger than the load they expect.' },
    { id: 'ancienttech', zone: 'zone4', name: 'Ancient technology', title: 'Ancient technology',
      story: 'Ancient engineers did remarkable things with simple tools, and some of their methods are still being worked out today.',
      dyk: ['Roman concrete sea walls have lasted about 2,000 years. Studies suggest seawater helped them grow stronger.',
            'Hero of Alexandria described a steam-powered spinning device, the aeolipile, in the 1st century CE.',
            'Archimedes is credited with the screw pump that still lifts water today.'],
      note: 'The Antikythera mechanism is often called the oldest known analogue computer. Its case file is in Zone 05.' },
    { id: 'ideas', zone: 'zone4', name: 'Big ideas & debate', title: 'Big ideas & debate',
      story: 'Socrates taught by asking questions instead of giving answers. The style is still called the Socratic method.',
      dyk: ['The Oxford Union has hosted debates since 1823.',
            'A “steelman” is the opposite of a strawman: arguing the strongest version of the other side.',
            'Ubuntu, often summed up as “I am because we are”, is a Southern African philosophy of shared humanity.'],
      note: 'Changing your mind because of good evidence is a strength, not a loss.' },
    { id: 'sumer', zone: 'zone5', name: 'Sumer', title: 'Sumer & Mesopotamia',
      story: 'Sumer, in what is now southern Iraq, is one of the earliest known civilisations. Around 3200 BCE its scribes developed cuneiform, among the first writing systems.',
      dyk: ['The Epic of Gilgamesh is one of the oldest surviving works of literature.',
            'Its flood story closely parallels Noah’s Ark and was written down centuries earlier.',
            'Mesopotamians counted in base 60, which is why an hour has 60 minutes.'],
      note: 'Zecharia Sitchin claimed the texts describe the Anunnaki as visitors from a planet called Nibiru. Most cuneiform scholars reject his translations.' },
    { id: 'atlantis', zone: 'zone5', name: 'Atlantis & lost worlds', title: 'Atlantis & lost civilisations',
      story: 'Atlantis first appears in Plato’s dialogues Timaeus and Critias, written around 360 BCE.',
      dyk: ['Plato placed it beyond the “Pillars of Hercules” and said it sank in a single day and night.',
            'The Bronze Age eruption of Thera (Santorini), which hit the Minoans, is a popular real-world candidate.',
            'Göbekli Tepe (c. 9500 BCE) is one reason writers like Graham Hancock argue civilisation is older than we think.'],
      note: 'In 2024 Graham Hancock and archaeologist Flint Dibble debated lost civilisations on The Joe Rogan Experience.' },
    { id: 'india', zone: 'zone5', name: 'Ancient India', title: 'Ancient India & the epics',
      story: 'The Indus Valley civilisation (c. 3300–1300 BCE) built planned cities with drains and standard-sized bricks. It is also where this mall gets its name.',
      dyk: ['The Mahabharata is one of the longest epic poems ever written, around 100,000 verses.',
            'Researcher Nilesh Oak uses astronomical references in the epics to argue they record events far older than mainstream dates.',
            'Mainstream scholars date the written Ramayana and Mahabharata to roughly the last centuries BCE.'],
      note: 'The vimanas, flying palaces in the epics, are a favourite of ancient-astronaut theorists.' },
    { id: 'egypt', zone: 'zone5', name: 'Ancient Egypt', title: 'Ancient Egypt',
      story: 'The Great Pyramid of Giza was built for the pharaoh Khufu around 2560 BCE.',
      dyk: ['It is the only one of the Seven Wonders of the Ancient World still standing.',
            'Workers’ villages and tombs near Giza show it was built by organised, paid Egyptian labour.',
            'Its sides are lined up with true north with remarkable accuracy.'],
      note: 'Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.' },
    { id: 'africa', zone: 'zone5', name: 'Ethiopia & Africa', title: 'Ethiopia & ancient Africa',
      story: 'Ethiopia’s Kingdom of Aksum was a major trading power from about the 1st to the 7th century CE, and minted its own coins.',
      dyk: ['Ethiopian tradition, recorded in the Kebra Nagast, says the Ark of the Covenant rests in Aksum, guarded by a single monk.',
            'Lucy, a 3.2-million-year-old human ancestor, was found in Ethiopia in 1974.',
            'Mapungubwe and Great Zimbabwe were powerful southern African kingdoms trading across the Indian Ocean.'],
      note: 'The churches of Lalibela were carved straight down into solid rock.' },
    { id: 'astronauts', zone: 'zone5', name: 'Ancient astronauts', title: 'Ancient astronaut theories',
      story: 'The ancient-astronaut idea says visitors from elsewhere shaped early human history. Erich von Däniken popularised it with Chariots of the Gods? in 1968.',
      dyk: ['Supporters point to the Nazca lines, the Dogon people’s star lore and megaliths such as Puma Punku.',
            'Archaeologists answer that ancient people had the skills, tools and time to build these themselves.',
            'The TV series Ancient Aliens has run since 2010.'],
      note: 'Whatever you conclude, asking “how did they do that?” is also how real archaeology starts.' },
    { id: 'declassified', zone: 'zone5', name: 'Declassified', title: 'Declassified files',
      story: 'Governments really did fund strange research, and some of it has been declassified. Much of it can be read in the CIA’s online reading room.',
      dyk: ['The Stargate Project studied “remote viewing” for US intelligence until it was closed in 1995.',
            'A 1983 US Army report on the “Gateway Process” was declassified and went viral online in 2021.',
            'A 1995 review found remote viewing had never produced intelligence that guided an operation.'],
      note: 'Project MKUltra, the CIA’s mind-control programme, was exposed in US Senate hearings in the 1970s.' },
    { id: 'pod-main', zone: 'zone6', name: 'The Podcast', title: 'The Section 31 Podcast',
      story: 'Long-form conversations from the sub-level: comics, games, ancient mysteries and big ideas, with guests from our community.',
      dyk: ['New episodes every week (placeholder).', 'Recorded live in store on podcast nights.', 'Send us a question and we may answer it on air.'],
      note: 'Want to be a guest? Use “Suggest a topic” below.' },
    { id: 'pod-ancient', zone: 'zone6', name: 'Ancient civilisations', title: 'Ancient civilisations channel',
      story: 'Short videos on lost worlds, the epics and mysteries that still have no answer. The companion to Zone 05.',
      dyk: ['New videos every week (placeholder).', 'Every video links to its case file in Zone 05.'], note: '' },
    { id: 'pod-gaming', zone: 'zone6', name: 'Gaming & streams', title: 'Gaming & streams',
      story: 'Gameplay, streams, tips and how-to videos from the Holodeck.',
      dyk: ['Stream schedule coming soon (placeholder).'], note: '' },
    { id: 'pod-comics', zone: 'zone6', name: 'Comic picks', title: 'Comic picks & unboxings',
      story: 'Wednesday-drop picks, unboxings and the stories behind the grails in the Evidence Locker.',
      dyk: ['A new picks video every Wednesday (placeholder).'], note: '' },
    { id: 'pod-bts', zone: 'zone6', name: 'Behind the scenes', title: 'Behind the scenes',
      story: 'How Section 31 is being built, from the first sketch to opening day.', dyk: [], note: '' },
    { id: 'pod-merch', zone: 'zone6', name: 'Merch', title: 'Merch & support',
      story: 'Wear the badge. Every purchase helps keep the transmissions coming.', dyk: [], note: '' },
    { id: 'sw-saber', zone: 'zone7', icon: 'saber', name: 'Lightsaber training', title: 'Lightsaber training',
      story: 'Lightsaber combat is now a real sport. Clubs train with LED duelling sabers, using stances, footwork and choreography, a bit like fencing with a glow.',
      dyk: ['In 2019 the French Fencing Federation officially recognised lightsaber duelling as a sport.',
            'Ludosport, founded in Italy in 2006, was one of the first lightsaber combat academies.',
            'In the original films the glowing blades were added afterwards, frame by frame, by hand-drawn rotoscoping.'],
      note: 'Training sabers have tough polycarbonate blades built to take hits. Display replicas are not made for duelling.' },
    { id: 'sw-lore', zone: 'zone7', icon: 'book', name: 'Lore & films', title: 'Lore & films',
      story: 'Star Wars (1977) was written and directed by George Lucas, and grew into films, series, books and comics across almost 50 years.',
      dyk: ['Lucas drew on Joseph Campbell’s idea of the “hero’s journey”.',
            'The opening text crawl was inspired by 1930s film serials such as Flash Gordon.',
            'Fans celebrate Star Wars Day on 4 May.'],
      note: 'Darth Vader was played on set by David Prowse and voiced by James Earl Jones.' },
    { id: 'sw-cosplay', zone: 'zone7', icon: 'robe', name: 'Cosplay', title: 'Costumes & cosplay',
      story: 'Cosplay brings the galaxy to life, from a simple hooded robe to full armour.',
      dyk: ['The 501st Legion, a worldwide costuming club founded in 1997, makes charity appearances in screen-accurate armour.',
            'Many great costumes start with cheap materials: craft foam, fabric and paint.',
            'A robe, belt and boots are the easiest place to start.'],
      note: 'Bring your costume to our monthly cosplay meet for photos and tips.' },
    { id: 'sw-gear', zone: 'zone7', icon: 'helmet', name: 'Sabers & gear', title: 'Sabers & gear',
      story: 'Training sabers, gloves and belt hooks for class and cosplay, plus collectables for the shelf at home.',
      dyk: ['Duelling sabers are rated by blade thickness and hilt strength, not just looks.'], note: '' }
  ],

  // Stock on the shelves. status: in | low | out | preorder. was = old price (shows as a markdown).
  // tag shows on the cover (WED = Wednesday drop). hue = cover colour until real photos are added.
  stock: [
    { name: 'Void Runners',         line: '#14',      shelf: 'comics', price: 'R95',  status: 'in',  tag: 'WED', hue: 205 },
    { name: 'The Hollow Sentinel',  line: '#3',       shelf: 'comics', price: 'R110', status: 'in',  tag: 'WED', hue: 270 },
    { name: 'Neon Tide',            line: '#7',       shelf: 'comics', price: 'R95',  status: 'low', tag: 'WED', hue: 330 },
    { name: 'Ashes of Tomorrow',    line: 'Vol. 2',   shelf: 'comics', price: 'R320', status: 'in',  hue: 20 },
    { name: 'Orbital Saints',       line: 'Omnibus',  shelf: 'comics', price: 'R690', status: 'preorder', hue: 45 },
    { name: 'Captain Vector',       line: '#1 · 1987', shelf: 'comics', price: 'R450', status: 'in', hue: 0 },
    { name: 'Shōnen manga',         line: 'Vol. 1',   shelf: 'manga', price: 'R180', status: 'in',  hue: 350 },
    { name: 'Manga box set',        line: 'Vols 1–10', shelf: 'manga', price: 'R1,450', status: 'low', hue: 15 },
    { name: 'Pokémon TCG booster',  line: 'Pack',     shelf: 'pokemon', price: 'R95',  status: 'in',  tag: 'NEW', hue: 50 },
    { name: 'Elite Trainer Box',    line: 'Pokémon TCG', shelf: 'pokemon', price: 'R1,100', status: 'in', hue: 200 },
    { name: 'Card sleeves',         line: '65 pack',  shelf: 'pokemon', price: 'R120', status: 'in',  hue: 160 },
    { name: 'Magic booster',        line: 'Pack',     shelf: 'tcg', price: 'R110', status: 'in',  hue: 25 },
    { name: 'Yu-Gi-Oh! deck',       line: 'Structure', shelf: 'tcg', price: 'R230', status: 'out', hue: 280 },
    { name: 'Star Wars figure',     line: '6-inch',   shelf: 'starwars', price: 'R550', status: 'in', hue: 220 },
    { name: 'Lightsaber replica',   line: 'Display',  shelf: 'starwars', price: 'R2,900', status: 'preorder', hue: 190 },
    { name: 'House scarf',          line: 'Hogwarts', shelf: 'potter', price: 'R390', status: 'in',  hue: 0 },
    { name: 'Wizard chess set',     line: 'Boxed',    shelf: 'potter', price: 'R1,600', status: 'low', hue: 35 },
    { name: 'The One Ring',         line: 'Replica',  shelf: 'lotr', price: 'R450', status: 'in',  hue: 42 },
    { name: 'Illustrated edition',  line: 'Hardback', shelf: 'lotr', price: 'R890', status: 'in',  hue: 120 },
    { name: 'Transformers figure',  line: 'Deluxe',   shelf: 'transformers', price: 'R480', status: 'in', hue: 0 },
    { name: 'Transformers figure',  line: 'Leader',   shelf: 'transformers', price: 'R1,250', status: 'low', hue: 270 },
    { name: 'Star Trek comic',      line: 'New issue', shelf: 'startrek', price: 'R95', status: 'in', tag: 'WED', hue: 210 },
    { name: 'Starship replica',     line: 'Die-cast', shelf: 'startrek', price: 'R890', status: 'in', hue: 230 },
    { name: 'Funko Pop! figure',    line: 'Vinyl',    shelf: 'collectables', price: 'R320', status: 'in', hue: 300 },
    { name: 'Premium statue',       line: '1:6 scale', shelf: 'collectables', price: 'R6,500', status: 'preorder', hue: 30 },
    { name: 'Display case',         line: 'Acrylic',  shelf: 'collectables', price: 'R450', was: 'R520', status: 'in', hue: 190 },
    { name: 'D&D starter set',      line: 'Boxed',    shelf: 'games', price: 'R450', status: 'in', hue: 0 },
    { name: 'Polyhedral dice',      line: '7-piece',  shelf: 'games', price: 'R150', status: 'in', hue: 260 },
    { name: 'Tournament chess set', line: 'Boxed',    shelf: 'chess', price: 'R650', status: 'in', hue: 0 },
    { name: 'Chess clock',          line: 'Digital',  shelf: 'chess', price: 'R480', status: 'low', hue: 210 },
    { name: 'Speed cube 3×3',       line: 'Magnetic', shelf: 'cubes', price: 'R290', status: 'in', tag: 'NEW', hue: 0 },
    { name: 'Classic cube 3×3',     line: 'Original', shelf: 'cubes', price: 'R220', status: 'in', hue: 45 },
    { name: 'Timer & mat',          line: 'Competition', shelf: 'cubes', price: 'R350', status: 'in', hue: 160 },
    { name: 'Go set',               line: '19×19',    shelf: 'boardgames', price: 'R790', status: 'preorder', hue: 90 },
    { name: 'Strategy board game',  line: '3–4 players', shelf: 'boardgames', price: 'R890', status: 'in', hue: 30 },
    { name: 'Puzzle box',           line: 'Wooden',   shelf: 'logic', price: 'R480', status: 'in', hue: 30 },
    { name: 'Burr puzzle set',      line: '6-piece',  shelf: 'logic', price: 'R260', status: 'in', hue: 20 },
    { name: 'Social deduction game', line: '5–10 players', shelf: 'people', price: 'R390', status: 'in', hue: 280 },
    { name: 'Team challenge',       line: 'Per team', shelf: 'people', price: 'R1,200', status: 'in', hue: 330, cta: 'Book a session' },
    { name: 'Flight yoke & throttle', line: 'USB',     shelf: 'flightsim', price: 'R3,500', status: 'preorder', hue: 200 },
    { name: 'Call of Duty (latest)',  line: 'PC / console', shelf: 'cod', price: 'R1,299', status: 'preorder', tag: 'NEW', hue: 100 },
    { name: 'Mobile trigger set',     line: 'COD Mobile', shelf: 'mobile', price: 'R180', status: 'in', hue: 15 },
    { name: 'Phone controller',       line: 'Bluetooth', shelf: 'mobile', price: 'R650', status: 'low', hue: 270 },
    { name: 'Gaming headset',         line: 'Wired',    shelf: 'pc', price: 'R890', status: 'in', hue: 300 },
    { name: 'Gaming mouse',           line: 'Wired',    shelf: 'pc', price: 'R650', status: 'in', hue: 180 },
    { name: 'Wireless controller',    line: 'Console / PC', shelf: 'console', price: 'R1,100', status: 'in', hue: 230 },
    { name: 'Retro mini console',     line: 'Plug & play', shelf: 'retro', price: 'R1,400', was: 'R1,600', status: 'in', hue: 40 },
    { name: 'Raspberry Pi kit',       line: 'Starter',  shelf: 'engineering', price: 'R1,650', status: 'in', hue: 340 },
    { name: 'Arduino starter kit',    line: 'Boxed',    shelf: 'engineering', price: 'R750', status: 'low', hue: 190 },
    { name: 'Python for beginners',   line: 'Book',     shelf: 'coding', price: 'R420', status: 'in', hue: 210 },
    { name: 'Security key',           line: '2FA, USB-C', shelf: 'cyber', price: 'R890', status: 'in', hue: 150 },
    { name: 'Ancient engineering',    line: 'Book',     shelf: 'ancienttech', price: 'R520', status: 'in', hue: 40 },
    { name: 'Philosophy graphic novel', line: 'Trade',  shelf: 'ideas', price: 'R380', status: 'in', hue: 280 },
    { name: 'Chariots of the Gods?', line: 'Erich von Däniken', shelf: 'astronauts', price: 'R320', status: 'in', hue: 30 },
    { name: 'Fingerprints of the Gods', line: 'Graham Hancock', shelf: 'atlantis', price: 'R380', status: 'in', hue: 200 },
    { name: 'The Epic of Gilgamesh', line: 'Translation', shelf: 'sumer', price: 'R250', status: 'in', hue: 40 },
    { name: 'Mahabharata',          line: 'Abridged',  shelf: 'india', price: 'R350', status: 'in', hue: 15 },
    { name: 'Kebra Nagast',         line: 'Translation', shelf: 'africa', price: 'R290', status: 'low', hue: 120 },
    { name: 'Atlas of Ancient Egypt', line: 'Hardback', shelf: 'egypt', price: 'R650', status: 'in', hue: 45 },
    { name: 'Section 31 tee',  line: 'Black',     shelf: 'pod-merch', price: 'R350', status: 'in', hue: 350 },
    { name: 'Classified mug',  line: 'Ceramic',   shelf: 'pod-merch', price: 'R180', status: 'in', hue: 190 },
    { name: 'Sticker pack',    line: '6 stickers', shelf: 'pod-merch', price: 'R60', status: 'in', hue: 50 },
    { name: 'Training saber',  line: 'LED, duel-rated', shelf: 'sw-gear', price: 'R1,800', status: 'preorder', hue: 140 },
    { name: 'Saber gloves',    line: 'Padded',          shelf: 'sw-gear', price: 'R250', status: 'in', hue: 30 },
    { name: 'Belt clip',       line: 'Quick release',   shelf: 'sw-gear', price: 'R150', status: 'in', hue: 210 },
    { name: 'Hooded robe',     line: 'Adult / kids',    shelf: 'sw-cosplay', price: 'R650', status: 'in', hue: 25 },
    { name: 'Helmet replica',  line: 'Display',         shelf: 'sw-gear', price: 'R2,500', status: 'preorder', hue: 0 }
  ],

  // Specials. ends: 'YYYY-MM-DD', 'month-end' (always the last day of this month) or '' (ongoing).
  // starts (optional): 'YYYY-MM-DD'. shelf (optional) adds a "View shelf" button.
  specials: [
    { badge: '2 for 1',   title: '2-for-1 back issues',        blurb: 'Buy any back issue and get a second of equal or lower value free.', shelf: 'comics', ends: '' },
    { badge: 'Month-end', title: 'Month-end collectables',     blurb: '15% off figures and statues until the end of the month.',           shelf: 'collectables', ends: 'month-end' },
    { badge: 'Bundle',    title: 'Trainer bundle',             blurb: 'Any Elite Trainer Box plus a pack of sleeves for R1,150.',            shelf: 'pokemon', ends: '2026-10-31' },
    { zone: 'zone2', badge: '2 for 1',   title: 'Bring a friend to cube class', blurb: 'Two seats for the price of one at any beginner Rubik’s cube lesson.', shelf: 'cubes', ends: '' },
    { zone: 'zone2', badge: 'Month-end', title: 'Month-end puzzle sale',       blurb: '10% off puzzles and board games until the end of the month.', shelf: 'logic', ends: 'month-end' },
    { zone: 'zone3', badge: 'Bundle',    title: 'Headset + mouse bundle',  blurb: 'Gaming headset and gaming mouse together for R1,350.', shelf: 'pc', ends: 'month-end' },
    { zone: 'zone3', badge: '2 for 1',   title: 'Retro hour',              blurb: 'Two hours on the retro cabinets for the price of one, every Friday before 18:00.', shelf: 'retro', ends: '' },
    { zone: 'zone4', badge: 'Month-end', title: 'Team table: 4 hours for 3', blurb: 'Book a team table for four hours and pay for three.', ends: 'month-end' },
    { zone: 'zone5', badge: 'Bundle', title: 'Theory starter pack', blurb: 'Any two Archive shop books for R550.', ends: 'month-end' },
    { zone: 'zone6', badge: 'Launch', title: 'Launch-month merch', blurb: '10% off all merch while the first episodes go live.', shelf: 'pod-merch', ends: 'month-end' },
    { zone: 'zone7', badge: 'Bundle', title: 'Starter kit', blurb: 'First lesson, gloves and a belt clip together for one price.', shelf: 'sw-saber', ends: 'month-end' }
  ],

  // Game news (newest first). date: YYYY-MM-DD. url optional.
  news: [
    { shelf: 'flightsim', date: '2026-10-02', title: 'Flight sim rig now open', blurb: 'Yoke, throttle and three screens. Book a slot or come in for a first flight.' },
    { shelf: 'cod',       date: '2026-09-30', title: 'COD Mobile challenge is live', blurb: 'Post your best Battle Royale eliminations this month. Top handle wins store credit.' },
    { shelf: 'retro',     date: '2026-09-25', title: 'Retro cabinet back online', blurb: 'The classic cabinet is fixed and ready for high-score hunters.' },
    { shelf: 'console',   date: '2026-09-20', title: 'Saturday tournaments return', blurb: 'Bracket play across the stations every Saturday afternoon.' }
  ],

  // Challenges with scoreboards. board: handle | score, best first. ends like specials.
  challenges: [
    { shelf: 'cod', title: 'COD Mobile: most eliminations', unit: 'Elims', prize: 'R300 store credit', ends: 'month-end',
      blurb: 'One Battle Royale match. Send a screenshot of your result screen.', board: [['NovaStrike', '18'], ['Q-Bit', '15'], ['Vektor', '12']] },
    { shelf: 'flightsim', title: 'Butter landing challenge', unit: 'ft/min', prize: 'Free sim hour', ends: 'month-end',
      blurb: 'Land at the featured airport. The softest touchdown wins.', board: [['SkyFox', '-62'], ['Mnemonic', '-88'], ['RubikRaven', '-120']] },
    { shelf: 'retro', title: 'Arcade high score', unit: 'Points', prize: 'Name on the cabinet', ends: '',
      blurb: 'Play in store on the retro cabinet. Staff record the score.', board: [['AAA', '98,450'], ['Cadet Nova', '76,200']] }
  ],

  // Watch, listen & read: links to podcasts, videos, research, books and archives. Paste the real link in url.
  media: [
    { shelf: 'atlantis', type: 'Podcast', source: 'The Joe Rogan Experience', title: 'Graham Hancock vs Flint Dibble: the lost-civilisation debate', url: '#',
      blurb: 'A writer and an archaeologist argue it out for hours. Hear both sides, then decide.' },
    { shelf: 'india', type: 'Research', source: 'Nilesh Oak', title: 'Dating the Ramayana and Mahabharata by the stars', url: '#',
      blurb: 'Astronomy-based dating of the Indian epics.' },
    { shelf: 'sumer', type: 'Video', source: 'Billy Carson', title: 'The Anunnaki and the Sumerian tablets', url: '#',
      blurb: 'An alternative reading of Sumerian myth.' },
    { shelf: 'egypt', type: 'Video', source: 'Jordan Maxwell', title: 'Ancient symbols and their meanings', url: '#',
      blurb: 'Talks on symbolism and its roots in the ancient world.' },
    { shelf: 'astronauts', type: 'Book', source: 'Erich von Däniken', title: 'Chariots of the Gods? (1968)', url: '#',
      blurb: 'The book that launched the ancient-astronaut theory.' },
    { shelf: 'declassified', type: 'Archive', source: 'CIA Reading Room', title: 'The Stargate and Gateway documents', url: '#',
      blurb: 'Read the declassified files yourself.' },
    { shelf: 'pod-main', type: 'Podcast', source: 'Section 31 Podcast', date: '2026-10-01', title: 'Episode 1: Welcome to the sub-level', url: '#',
      blurb: 'Who we are, what Section 31 is, and what is coming next.' },
    { shelf: 'pod-ancient', type: 'Video', source: 'Our channel', date: '2026-09-28', title: 'The Indus script: the code nobody can crack', url: '#',
      blurb: 'Thousands of inscriptions, no translation. Why it is still unsolved.' },
    { shelf: 'pod-comics', type: 'Video', source: 'Our channel', date: '2026-09-30', title: 'Wednesday drop: this week’s picks', url: '#',
      blurb: 'Five new releases worth a look.' },
    { shelf: 'pod-gaming', type: 'Video', source: 'Our channel', date: '2026-09-24', title: 'Flight sim: how to land softly', url: '#',
      blurb: 'Tips for the butter landing challenge.' },
    { shelf: 'pod-bts', type: 'Video', source: 'Our channel', date: '2026-09-20', title: 'Building the sub-level', url: '#',
      blurb: 'A first look at how the store is coming together.' },
    { shelf: 'sw-saber', type: 'Video', source: 'Our channel', title: 'Saber basics: your first three stances', url: '#',
      blurb: 'Practise at home before your first class.' },
    { shelf: 'sw-lore', type: 'Video', source: 'Our channel', title: 'Watch order explained', url: '#',
      blurb: 'Release order or story order? A quick guide for new fans.' }
  ],

  // Topics on the table: conversations, debates and ideas sessions. status: open | soon.
  topics: [
    { shelf: 'ideas', title: 'Will AI make us smarter or lazier?', format: 'Debate', when: 'Monthly · 1st Thursday 18:30', host: 'Host (placeholder)', status: 'open',
      blurb: 'Two sides, a moderator and a vote at the end. Everyone gets a turn.' },
    { shelf: 'ancienttech', title: 'How were the pyramids really built?', format: 'Open chat', when: 'Saturdays 15:00', host: 'Host (placeholder)', status: 'open',
      blurb: 'Ramps, levers and logistics. Bring your theory, and your evidence.' },
    { shelf: 'cyber', title: 'Is a password manager actually safe?', format: 'Open chat', when: 'At Study Hall', host: 'Mentor (placeholder)', status: 'open',
      blurb: 'How they work, what can go wrong, and what we would recommend to family.' },
    { shelf: 'engineering', title: 'What should we build next?', format: 'Ideas session', when: 'Starting soon', status: 'soon',
      blurb: 'Pitch a project for build night. The best idea gets built.' },
    { shelf: 'atlantis', title: 'Was there an advanced civilisation before the Ice Age?', format: 'Theory night', when: 'Monthly · 3rd Wednesday 18:30', host: 'Host (placeholder)', status: 'open',
      blurb: 'Evidence on one side, theories on the other. Everyone gets a turn.' },
    { shelf: 'india', title: 'The epics: myth, memory or history?', format: 'Open chat', when: 'Saturdays 16:00', host: 'Host (placeholder)', status: 'open',
      blurb: 'What the Ramayana and Mahabharata might remember, and how we could test it.' },
    { shelf: 'astronauts', title: 'Ancient astronauts: the case for and against', format: 'Debate', when: 'Starting soon', status: 'soon',
      blurb: 'Two teams, one moderator, and a vote at the end.' },
    { shelf: 'pod-main', title: 'Live recording: ask us anything', format: 'Live show', when: 'Monthly · 3rd Wednesday 18:30', host: 'Section 31 crew', status: 'open',
      blurb: 'Sit in on an episode and put your question to the panel.' },
    { shelf: 'pod-main', title: 'Guest episode: a local speedcuber', format: 'Upcoming episode', when: 'Coming soon', status: 'soon',
      blurb: 'How to get from your first solve to competitions.' },
    { shelf: 'sw-lore', title: 'Which trilogy is the best?', format: 'Debate', when: 'Monthly · last Saturday 15:00', host: 'Host (placeholder)', status: 'open',
      blurb: 'Original, prequel or sequel. Make your case.' },
    { shelf: 'sw-cosplay', title: 'Build your own saber hilt', format: 'Workshop', when: 'Starting soon', status: 'soon',
      blurb: 'Design and build a display hilt from simple parts.' }
  ],

  // Zone 06: where people can listen. Paste your real links.
  podcast: {
    platforms: [{ name: 'Spotify', url: '#' }, { name: 'Apple Podcasts', url: '#' }, { name: 'YouTube', url: '#' }, { name: 'TikTok', url: '#' }, { name: 'Instagram', url: '#' }]
  },

  // Book a table: the choices in the booking form.
  tables: {
    purposes: ['Team meeting', 'DevOps sprint', 'Study group', 'Debate circle', 'Workshop', 'Quiet focus'],
    slots: ['09:00 – 12:00', '12:00 – 15:00', '15:00 – 18:00'],
    sizes: ['1 person', '2 – 4 people', '5 – 8 people', '9+ people']
  },

  // Lessons (learning zones). Add a lesson when a teacher is available.
  // status: open (taking bookings) | full (waitlist) | paused (teacher away). slots: one time per line in the admin.
  lessons: [
    { shelf: 'chess', title: 'Chess for beginners', level: 'Beginner', ages: '7+', teacher: 'Coach (placeholder)', slots: ['Saturday 10:00', 'Wednesday 16:00'], length: '60 min', seats: 6, price: 'R120 per lesson', status: 'open',
      blurb: 'How the pieces move, basic tactics and your first checkmates.' },
    { shelf: 'chess', title: 'Chess club: tactics & openings', level: 'Intermediate', ages: '10+', teacher: 'Coach (placeholder)', slots: ['Thursday 17:00'], length: '90 min', seats: 8, price: 'R150 per lesson', status: 'open',
      blurb: 'Openings, middlegame plans and puzzles, with a practice game every week.' },
    { shelf: 'cubes', title: 'Solve your first Rubik’s cube', level: 'Beginner', ages: '8+', teacher: 'Coach (placeholder)', slots: ['Saturday 12:00', 'Tuesday 16:00'], length: '90 min', seats: 8, price: 'R250', status: 'open',
      blurb: 'The layer-by-layer method, step by step. Most people leave able to solve it.' },
    { shelf: 'cubes', title: 'Speedcubing: CFOP method', level: 'Advanced', ages: '10+', teacher: 'Coach (placeholder)', slots: ['Friday 16:30'], length: '60 min', seats: 6, price: 'R180 per lesson', status: 'full',
      blurb: 'Cross, F2L, OLL and PLL: the method most fast cubers use.' },
    { shelf: 'boardgames', title: 'Learn Go', level: 'Beginner', ages: '10+', teacher: 'Coach (placeholder)', slots: ['Saturday 14:00'], length: '60 min', seats: 6, price: 'R120 per lesson', status: 'paused',
      blurb: 'Simple rules, endless depth. Start on a small 9×9 board.' },
    { shelf: 'boardgames', title: 'Strategy game school', level: 'All levels', ages: '12+', teacher: 'Coach (placeholder)', slots: ['Friday 18:00'], length: '2 hours', seats: 12, price: 'R100', status: 'open',
      blurb: 'Learn a modern strategy game each month, then play it properly.' },
    { shelf: 'flightsim', title: 'Flight sim: your first flight', level: 'Beginner', ages: '10+', teacher: 'Coach (placeholder)', slots: ['Saturday 09:00', 'Thursday 16:00'], length: '60 min', seats: 2, price: 'R150', status: 'open',
      blurb: 'Take-off, a circuit and a landing in a light aircraft, on our sim rig.' },
    { shelf: 'cod', title: 'COD Mobile: settings & aim', level: 'All levels', ages: '13+', teacher: 'Coach (placeholder)', slots: ['Friday 16:00'], length: '60 min', seats: 8, price: 'R100', status: 'open',
      blurb: 'Controls, sensitivity, loadouts and movement that win gunfights.' },
    { shelf: 'pc', title: 'Esports team play', level: 'Intermediate', ages: '13+', teacher: 'Coach (placeholder)', slots: ['Saturday 15:00'], length: '90 min', seats: 10, price: 'R120', status: 'paused',
      blurb: 'Call-outs, roles and reviewing your own matches like the pros.' },
    { shelf: 'coding', title: 'Code club: Python from zero', level: 'Beginner', ages: '12+', teacher: 'Mentor (placeholder)', slots: ['Tuesday 17:30', 'Saturday 10:00'], length: '90 min', seats: 10, price: 'R120 per session', status: 'open',
      blurb: 'Variables to your first small app, one session at a time.' },
    { shelf: 'cyber', title: 'CTF practice squad', level: 'Intermediate', ages: '15+', teacher: 'Mentor (placeholder)', slots: ['Friday 18:00'], length: '2 hours', seats: 12, price: 'R100', status: 'open',
      blurb: 'Safe, legal hacking puzzles in a sandbox. Learn by solving.' },
    { shelf: 'engineering', title: 'Arduino build night', level: 'All levels', ages: '12+', teacher: 'Mentor (placeholder)', slots: ['Wednesday 17:30'], length: '2 hours', seats: 8, price: 'R200 (kit extra)', status: 'open',
      blurb: 'Sensors, motors and LEDs. Build something that works by the end of the night.' },
    { shelf: 'ideas', title: 'Study group: open table', level: 'All levels', ages: 'All ages', teacher: 'Hosted', slots: ['Tuesday 17:30', 'Thursday 17:30'], length: '2 hours', seats: 16, price: 'Day pass', status: 'open',
      blurb: 'Bring your work. Quiet focus, good company, someone to ask.' },
    { shelf: 'sw-saber', title: 'Saber basics: stances & guards', level: 'Beginner', ages: '8+', teacher: 'Instructor (placeholder)', slots: ['Saturday 10:00', 'Wednesday 16:30'], length: '60 min', seats: 10, price: 'R150 per lesson', status: 'open',
      blurb: 'How to hold a saber safely, your first stances, guards and a simple combo.' },
    { shelf: 'sw-saber', title: 'Spins & flourishes', level: 'Intermediate', ages: '12+', teacher: 'Instructor (placeholder)', slots: ['Wednesday 17:30'], length: '60 min', seats: 8, price: 'R150 per lesson', status: 'open',
      blurb: 'Wrist spins, figure-eights and moves that look great on camera.' },
    { shelf: 'sw-saber', title: 'Duel choreography', level: 'Advanced', ages: '14+', teacher: 'Instructor (placeholder)', slots: ['Friday 18:00'], length: '90 min', seats: 8, price: 'R180 per lesson', status: 'full',
      blurb: 'Learn and perform a full partner duel, step by step.' },
    { shelf: 'sw-saber', title: 'Kids’ saber class', level: 'All levels', ages: '6–11', teacher: 'Instructor (placeholder)', slots: ['Saturday 12:00'], length: '45 min', seats: 10, price: 'R120', status: 'open',
      blurb: 'Fun, safe moves and games with soft training sabers.' }
  ],

  locker: [
    { id: '031-A', featured: true, title: 'Atlas Syndicate #1',          era: 'Silver Age', grade: 'CGC 8.5 (placeholder)', note: 'Key issue — first appearance',  price: 'On enquiry' },
    { id: '031-B', title: 'Midnight Courier #1',         era: 'Bronze Age', grade: 'CGC 9.2 (placeholder)', note: 'Rare retailer variant',        price: 'On enquiry' },
    { id: '031-C', title: 'Golden Meridian Annual #1',   era: 'Golden Age', grade: 'Raw VG+ (placeholder)', note: 'Estate find, single owner',    price: 'On enquiry' }
  ],

  puzzle: {                                // Caesar shift of 3
    cipher: 'WKH DUFKLYH UHPHPEHUV',
    answer: 'THE ARCHIVE REMEMBERS',
    hint: 'Every letter has been pushed three places along the alphabet. Pull them back.',
    reward: 'KM-31A7'
  },

  board: [['1', 'Cadet Nova', '00:19.8'], ['2', 'RubikRaven', '00:21.4'], ['3', 'Q-Bit', '00:23.0'], ['4', 'Vektor', '00:24.7'], ['5', 'Mnemonic', '00:26.1']],

  // "We buy collections" form: the two dropdowns.
  collection: {
    types: ['Comics (floppies)', 'Trades & graphic novels', 'Collectibles & toys', 'A bit of everything'],
    sizes: ['Under 50 items', '50 – 200 items', '200 – 1,000 items', '1,000+ (longboxes!)']
  },

  // kind: weekly (dow 0=Sun…6=Sat) or monthly (nth occurrence of dow in the month)
  events: [
    { zone: 'zone2', name: 'Challenge Night',            blurb: 'Puzzles, logic games and a new team scenario every week.',  kind: 'weekly',  dow: 4, time: '18:00', cta: 'Save my seat' },
    { zone: 'zone2', name: 'Speed-cube Showdown',        blurb: 'Monthly head-to-head. All skill levels welcome.',           kind: 'monthly', nth: 2, dow: 6, time: '14:00', cta: 'Save my seat' },
    { zone: 'zone3', name: 'Program 01 · Retro Arcade Night', blurb: 'Classic cabinets and couch co-op.',                    kind: 'weekly',  dow: 5, time: '18:00', cta: 'Run program' },
    { zone: 'zone3', name: 'Program 02 · Saturday Tournament', blurb: 'Bracketed play across the stations. Prizes on the line.', kind: 'weekly', dow: 6, time: '14:00', cta: 'Run program' },
    { zone: 'zone3', name: 'Program 03 · Family Co-op Sunday', blurb: 'Open to all ages. Team up against the game.',     kind: 'monthly', nth: 1, dow: 0, time: '12:00', cta: 'Run program' },
    { zone: 'zone4', name: 'Logic Prevails — monthly talk', blurb: 'Security, DevOps and engineering, explained plainly.',   kind: 'monthly', nth: 1, dow: 4, time: '18:30', cta: 'Save my seat' },
    { zone: 'zone4', name: 'Capture-the-Flag Night',     blurb: 'Friendly hacking puzzles in a safe sandbox.',               kind: 'monthly', nth: 3, dow: 5, time: '19:00', cta: 'Save my seat' },
    { zone: 'zone4', name: 'Study Hall — open table',    blurb: 'Bring your laptop. Quiet focus, good company.',             kind: 'weekly',  dow: 2, time: '17:30', cta: 'Save my seat' },
    { zone: 'zone5', name: 'Unsolved File of the Week',  blurb: 'A new case file opens every Tuesday. Bring your theory to the counter.', kind: 'weekly', dow: 2, time: '10:00', cta: 'Remind me' },
    { zone: 'zone5', name: 'Case File Night: open debate', blurb: 'One mystery, evidence versus theory. You decide.',       kind: 'monthly', nth: 2, dow: 2, time: '18:30', cta: 'Save my seat' },
    { zone: 'zone6', name: 'Podcast: live recording',    blurb: 'Sit in on an episode and put your question to the panel.', kind: 'monthly', nth: 3, dow: 3, time: '18:30', cta: 'Save my seat' },
    { zone: 'zone5', name: 'Junior Archaeologists',      blurb: 'Dig boxes and decoding games for younger agents. All ages.', kind: 'monthly', nth: 4, dow: 6, time: '10:00', cta: 'Save my seat' },
    { zone: 'zone7', name: 'Saber training night', blurb: 'Open practice for all levels. Training sabers provided.', kind: 'weekly', dow: 3, time: '18:00', cta: 'Save my seat' },
    { zone: 'zone7', name: 'Cosplay meet', blurb: 'Bring your costume for photos, tips and a group shot.', kind: 'monthly', nth: 1, dow: 6, time: '14:00', cta: 'Save my seat' }
  ],

  portals: [
    { name: 'Discord',        url: '#' },
    { name: 'Twitch',         url: '#' },
    { name: 'YouTube',        url: '#' },
    { name: 'Game servers',   url: '#' },
    { name: 'Indus Valley',   url: 'https://indusvalley.earth/' }
  ],

  prices: [
    ['Team table (per hour)',      'R150'],
    ['Day pass — open table',      'R90'],
    ['Workshop seat',              'R250'],
    ['Whole-corner private hire',  'On enquiry']
  ],

  // Add  url: 'https://...'  to a briefing and clicking it opens that page.
  briefings: [
    { title: 'Zero-trust for small teams, in five minutes', tag: 'Security', mins: '5 min read', blurb: 'What it actually means, and the three habits that get you most of the way there.' },
    { title: 'Your first CI pipeline, without the jargon',  tag: 'DevOps',   mins: '7 min read', blurb: 'From “it works on my machine” to an automatic check on every change.' },
    { title: 'Spotting a phish: the five tells',            tag: 'Security', mins: '4 min read', blurb: 'The small details that give a fake message away — and what to do next.' }
  ],

  // Zone 05 — Ancient X-Files. featured:true = "Unsolved file of the week".
  ancients: {
    shelf: ['Ancient-history graphic novels', 'Mythology comics', 'Lost-worlds sci-fi', 'Archaeology for young readers', 'Documentaries & guides'],
    files: [
      { id: 'AX-01', shelf: 'india', featured: true, title: 'The Indus script', where: 'Harappa & Mohenjo-daro (Pakistan / India)', when: 'c. 2600 – 1900 BCE', status: 'Undeciphered',
        evidence: 'Thousands of short inscriptions, mostly on small stone seals, using roughly 400 signs. No bilingual text has ever been found to unlock them.',
        theory: 'Many scholars link it to an early Dravidian language; others to Indo-Aryan or a lost tongue. A few argue it isn’t full writing at all.' },
      { id: 'AX-02', shelf: 'atlantis', title: 'The Antikythera mechanism', where: 'Shipwreck off Antikythera, Greece', when: 'c. 2nd – 1st century BCE (found 1901)', status: 'Partly decoded',
        evidence: 'A hand-cranked bronze gear train that tracked the sun, the moon and eclipse cycles. X-ray scans recovered hidden inscriptions, a built-in user guide.',
        theory: 'Nobody knows who built it. Nothing this complex survives again for over a thousand years, so were there others?' },
      { id: 'AX-03', shelf: 'atlantis', title: 'Göbekli Tepe', where: 'Şanlıurfa, Türkiye', when: 'c. 9500 BCE', status: 'Still being excavated',
        evidence: 'Huge carved stone pillars raised by hunter-gatherers, thousands of years before Stonehenge and before farming took hold.',
        theory: 'A feasting and gathering place? It challenges the old idea that towns came first and monuments later.' },
      { id: 'AX-04', shelf: 'astronauts', title: 'The Nazca lines', where: 'Nazca Desert, Peru', when: 'c. 500 BCE – 500 CE', status: 'Purpose debated',
        evidence: 'Giant figures and dead-straight lines scraped into the desert floor, best seen from the air. New figures are still being found with drones and AI.',
        theory: 'Ritual walking paths, markers linked to water and rain, or sky-watching: researchers still argue over the main purpose.' },
      { id: 'AX-05', shelf: 'africa', title: 'The golden rhino of Mapungubwe', where: 'Limpopo Valley, South Africa', when: 'c. 1220 – 1290 CE', status: 'Partly solved',
        evidence: 'A kingdom that traded gold and ivory across the Indian Ocean. A small gold-foil rhino was found in a royal grave in 1933.',
        theory: 'Why was it abandoned around 1300? A drier, colder climate is a leading explanation, with power moving north to Great Zimbabwe.' },
      { id: 'AX-06', shelf: 'sumer', title: 'The Anunnaki', where: 'Sumer (southern Iraq)', when: 'c. 3000 – 2000 BCE', status: 'Contested',
        evidence: 'In Sumerian and Akkadian texts the Anunnaki are a group of gods linked to the sky god An. Cuneiform specialists read them as deities in a religious system.',
        theory: 'Zecharia Sitchin argued they were visitors from the planet Nibiru who engineered humans. Writers such as Billy Carson explore versions of this idea.' },
      { id: 'AX-07', shelf: 'egypt', title: 'How the Great Pyramid was built', where: 'Giza, Egypt', when: 'c. 2560 BCE', status: 'Partly solved',
        evidence: 'The Diary of Merer, a 4,500-year-old logbook, records boat crews shipping limestone to Giza. Ramps, copper tools and a huge organised workforce explain much of it.',
        theory: 'Some argue the precision points to lost technology or an older civilisation, and that the accepted dates are wrong.' },
      { id: 'AX-08', shelf: 'africa', title: 'The Ark in Aksum', where: 'Aksum, Ethiopia', when: 'Tradition, date unknown', status: 'Unverified',
        evidence: 'The Ethiopian Orthodox Church says the Ark is kept in the Chapel of the Tablet in Aksum. No outsider is allowed to see it.',
        theory: 'The Kebra Nagast says Menelik I, son of King Solomon and the Queen of Sheba, brought it to Ethiopia. Others think it was lost or destroyed in ancient Jerusalem.' },
      { id: 'AX-09', shelf: 'declassified', title: 'Project Stargate', where: 'Fort Meade, Maryland, USA', when: '1978 – 1995', status: 'Declassified',
        evidence: 'US intelligence funded “remote viewing” research for about two decades. A 1995 review found it had never produced intelligence that guided an operation.',
        theory: 'Some former viewers say it worked better than the review admits. Others see it as a sign of how far the Cold War pushed fringe ideas.' }
    ],
    channels: [                            // your ancient civilisations channel and podcast
      { name: 'Instagram', url: '#' },
      { name: 'TikTok',    url: '#' },
      { name: 'Podcast',   url: '#' }
    ]
  },

  tiers: [
    { key: 'visitor',   name: 'Visitor',   blurb: 'Walk right in. No sign-up.',       perks: ['Browse the whole facility', 'See the weekly puzzle'], cta: null },
    { key: 'cadet',     name: 'Cadet',     blurb: 'Pick a handle. That’s it.',        perks: ['Your name on the leaderboard', 'Puzzle rewards saved to you', 'Pull-list shortcuts'], cta: 'Request clearance' },
    { key: 'operative', name: 'Operative', blurb: 'For regulars — by invitation.',    perks: ['First look at the Evidence Locker', 'Priority on Wednesday drops', 'Team-table discounts'], cta: null }
  ]
};
